// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChPMyfrwWe3NimNu_SggGW3wcp4uFoslQ',
    appId: '1:273723176822:web:786cb64720230e6ce32c57',
    messagingSenderId: '273723176822',
    projectId: 'qrproject-aeada',
    authDomain: 'qrproject-aeada.firebaseapp.com',
    storageBucket: 'qrproject-aeada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrCsSBog6v2tVpDNrqqssUBVoEt4i69_Q',
    appId: '1:273723176822:android:8bd47792d2d424bce32c57',
    messagingSenderId: '273723176822',
    projectId: 'qrproject-aeada',
    storageBucket: 'qrproject-aeada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuS3U_ptpi5-iF-e_fdcv4OZXhZ_OjHM',
    appId: '1:273723176822:ios:280519e0e88f11b9e32c57',
    messagingSenderId: '273723176822',
    projectId: 'qrproject-aeada',
    storageBucket: 'qrproject-aeada.firebasestorage.app',
    iosBundleId: 'com.example.qr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuS3U_ptpi5-iF-e_fdcv4OZXhZ_OjHM',
    appId: '1:273723176822:ios:280519e0e88f11b9e32c57',
    messagingSenderId: '273723176822',
    projectId: 'qrproject-aeada',
    storageBucket: 'qrproject-aeada.firebasestorage.app',
    iosBundleId: 'com.example.qr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChPMyfrwWe3NimNu_SggGW3wcp4uFoslQ',
    appId: '1:273723176822:web:b2292f04fdc77f34e32c57',
    messagingSenderId: '273723176822',
    projectId: 'qrproject-aeada',
    authDomain: 'qrproject-aeada.firebaseapp.com',
    storageBucket: 'qrproject-aeada.firebasestorage.app',
  );
}
